name: kstuff-toggle

on:
  push:
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "**/*.txt"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  payload-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang-18 lld-18 xxd yasm nasm

      - name: Install toolchain
        run: |
          wget https://github.com/ps5-payload-dev/pacbrew-repo/releases/download/v0.29/ps5-payload-dev.tar.gz
          sudo tar xf ps5-payload-dev.tar.gz -C /

      - name: Build all payloads
        run: |
          export PS5_PAYLOAD_SDK=/opt/ps5-payload-sdk
          make

      - name: Upload Payload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Kstuff-Toggle
          path: |
            ./kstuff-toggle-1.elf
            ./kstuff-toggle-2.elf
            ./kstuff-toggle-3.elf
            ./homebrew.js
          if-no-files-found: error
